#include "FilterRegistrationDefs.hpp"
#include "FspMonitor.hpp"

namespace FSP
{
    static constexpr FLT_CONTEXT_REGISTRATION gContextsRegistration[] =
    {
        { FLT_CONTEXT_END }
    };

    static constexpr FLT_OPERATION_REGISTRATION gCallbacksRegistration[] =
    {
        {
            IRP_MJ_CREATE,
            0,
            nullptr,
            nullptr
        },
        {
            IRP_MJ_CREATE_NAMED_PIPE,
            0,
            nullptr,
            nullptr
        },
        {
            IRP_MJ_CLOSE,
            0,
            nullptr,
            nullptr
        },
        {
            IRP_MJ_READ,
            0,
            nullptr,
            nullptr
        },
        {
            IRP_MJ_WRITE,
            0,
            nullptr,
            nullptr
        },
        {
            IRP_MJ_QUERY_INFORMATION,
            0,
            nullptr,
            nullptr
        },
        {
            IRP_MJ_SET_INFORMATION,
            0,
            nullptr,
            nullptr
        },
        {
            IRP_MJ_QUERY_EA,
            0,
            nullptr,
            nullptr
        },
        {
            IRP_MJ_SET_EA,
            0,
            nullptr,
            nullptr
        },
        {
            IRP_MJ_FLUSH_BUFFERS,
            0,
            nullptr,
            nullptr
        },
        {
            IRP_MJ_QUERY_VOLUME_INFORMATION,
            0,
            nullptr,
            nullptr
        },
        {
            IRP_MJ_SET_VOLUME_INFORMATION,
            0,
            nullptr,
            nullptr
        },
        {
            IRP_MJ_DIRECTORY_CONTROL,
            0,
            nullptr,
            nullptr
        },
        {
            IRP_MJ_FILE_SYSTEM_CONTROL,
            0,
            nullptr,
            nullptr
        },
        {
            IRP_MJ_DEVICE_CONTROL,
            0,
            nullptr,
            nullptr
        },
        {
            IRP_MJ_INTERNAL_DEVICE_CONTROL,
            0,
            nullptr,
            nullptr
        },
        {
            IRP_MJ_SHUTDOWN,
            0,
            nullptr,
            nullptr
        },                                         //post operations not supported
        {
            IRP_MJ_LOCK_CONTROL,
            0,
            nullptr,
            nullptr
        },
        {
            IRP_MJ_CLEANUP,
            0,
            nullptr,
            nullptr
        },
        {
            IRP_MJ_CREATE_MAILSLOT,
            0,
            nullptr,
            nullptr
        },
        {
            IRP_MJ_QUERY_SECURITY,
            0,
            nullptr,
            nullptr
        },
        {
            IRP_MJ_SET_SECURITY,
            0,
            nullptr,
            nullptr
        },
        {
            IRP_MJ_QUERY_QUOTA,
            0,
            nullptr,
            nullptr
        },
        {
            IRP_MJ_SET_QUOTA,
            0,
            nullptr,
            nullptr
        },
        {
            IRP_MJ_PNP,
            0,
            nullptr,
            nullptr
        },
        {
            IRP_MJ_ACQUIRE_FOR_SECTION_SYNCHRONIZATION,
            0,
            nullptr,
            nullptr
        },
        {
            IRP_MJ_RELEASE_FOR_SECTION_SYNCHRONIZATION,
            0,
            nullptr,
            nullptr
        },
        {
            IRP_MJ_ACQUIRE_FOR_MOD_WRITE,
            0,
            nullptr,
            nullptr
        },
        {
            IRP_MJ_RELEASE_FOR_MOD_WRITE,
            0,
            nullptr,
            nullptr
        },
        {
            IRP_MJ_ACQUIRE_FOR_CC_FLUSH,
            0,
            nullptr,
            nullptr
        },
        {
            IRP_MJ_RELEASE_FOR_CC_FLUSH,
            0,
            nullptr,
            nullptr
        },
        {
            IRP_MJ_FAST_IO_CHECK_IF_POSSIBLE,
            0,
            nullptr,
            nullptr
        },
        {
            IRP_MJ_NETWORK_QUERY_OPEN,
            0,
            nullptr,
            nullptr
        },
        {
            IRP_MJ_MDL_READ,
            0,
            nullptr,
            nullptr
        },
        {
            IRP_MJ_MDL_READ_COMPLETE,
            0,
            nullptr,
            nullptr
        },
        {
            IRP_MJ_PREPARE_MDL_WRITE,
            0,
            nullptr,
            nullptr
        },
        {
            IRP_MJ_MDL_WRITE_COMPLETE,
            0,
            nullptr,
            nullptr,
        },
        {
            IRP_MJ_VOLUME_MOUNT,
            0,
            nullptr,
            nullptr
        },
        {
            IRP_MJ_VOLUME_DISMOUNT,
            0,
            nullptr,
            nullptr,
        },
        { IRP_MJ_OPERATION_END }
    };

    const FLT_REGISTRATION gFilterRegistration =
    {

        sizeof(FLT_REGISTRATION),                           //  Size
        FLT_REGISTRATION_VERSION,                           //  Version
        FLTFL_REGISTRATION_DO_NOT_SUPPORT_SERVICE_STOP,     //  Flags

        gContextsRegistration,                              //  Context
        gCallbacksRegistration,                             //  Operation callbacks

        FSP::FspMonitor::FspmUnload,

        FSP::FspMonitor::FspmInstanceSetup,
        FSP::FspMonitor::FspmInstanceQueryTeardown,
        FSP::FspMonitor::FspmInstanceTeardownStart,
        FSP::FspMonitor::FspmInstanceTeardownComplete,

        nullptr,                                            //  GenerateFileName
        nullptr,                                            //  GenerateDestinationFileName
        nullptr                                             //  NormalizeNameComponent
    };
}